[package]
name = "windy-daily-utils-lib"
version = "0.1.0"
authors = ["windy <kugoo11v12@126.com>"]
description = "A daily utils lib for me."
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
